### ISSUE TITLE
unknown error

### ISSUE THREAD

**Issue by spacepcde** [HarvsG/ha-glinet-integration#5]
I use Home Assistant OS on a Raspberry Pi 4 with a GL-X3000. When setting up the integration, after confirming the IP + password, the integration reports "unknown".

**Comment by HarvsG** [comment]
Anything in the logs?

**Comment by oceanpix** [comment]
Not sure if is the same error but after adding the integration and configuring Mt300n-v2 on HAS this is the error I get straight away in the log

Error setting up entry GL-inet Mt300n-v2 for glinet
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/glinet/__init__.py", line 53, in async_setup_entry
    await router.setup()
  File "/config/custom_components/glinet/router.py", line 131, in setup
    entity_registry = er_helper.async_get(self.hass)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: async_get() takes 1 positional argument but 2 were given

**Comment by slayer** [comment]
UPD: nvm, works with ver4
